/* Respostas de aluno para medir o corretor (regras + IA).
   [questão, resposta, rótulo]
   'right' = deve ser aceita; 'maybe' = aceitável como sugestão; 'wrong' = não pode ser aceita. */
export const CASES = [
  // ---------- respostas curtas ----------
  ['antes1#7','cem','right'], ['antes1#7','Cem','right'], ['antes1#7','por cem','right'], ['antes1#7','100','maybe'], ['antes1#7','mil','wrong'], ['antes1#7','dez','wrong'],
  ['antes2#7','regra de 3','right'], ['antes2#7','Regra de três simples','right'], ['antes2#7','a regra de três','right'], ['antes2#7','proporção','maybe'], ['antes2#7','porcentagem','wrong'], ['antes2#7','média ponderada','wrong'],
  ['antes3#6','saldo','right'], ['antes3#6','Saldo','right'], ['antes3#6','o saldo final','right'], ['antes3#6','é o saldo da conta','right'], ['antes3#6','resultado','wrong'], ['antes3#6','lucro','wrong'], ['antes3#6','extrato','wrong'], ['antes3#6','diferença','wrong'],
  ['antes4#7','montante','right'], ['antes4#7','valor futuro','right'], ['antes4#7','o montante final','right'], ['antes4#7','total','maybe'], ['antes4#7','juros','wrong'], ['antes4#7','capital','wrong'], ['antes4#7','taxa','wrong'], ['antes4#7','juros compostos','wrong'],
  ['antes10#5','ponderada','right'], ['antes10#5','média ponderada','right'], ['antes10#5','aritmética','wrong'], ['antes10#5','simples','wrong'], ['antes10#5','mediana','wrong'],
  ['antes5#4','CNPJ','right'], ['antes5#4','cnpj da empresa','right'], ['antes5#4','Cadastro Nacional da Pessoa Jurídica','right'], ['antes5#4','CPF','wrong'], ['antes5#4','inscrição estadual','wrong'],
  ['antes6#6','prazo','right'], ['antes6#6','a prazo','right'], ['antes6#6','fiado','right'], ['antes6#6','parcelado','maybe'], ['antes6#6','vista','wrong'], ['antes6#6','à vista','wrong'],
  ['antes7#4','nota fiscal','right'], ['antes7#4','NF-e','right'], ['antes7#4','nota fiscal eletrônica','right'], ['antes7#4','a nota fiscal','right'], ['antes7#4','cupom fiscal','maybe'], ['antes7#4','recibo','wrong'], ['antes7#4','boleto','wrong'], ['antes7#4','duplicata','wrong'],
  ['antes8#5','Caixa','right'], ['antes8#5','conta caixa','right'], ['antes8#5','caixa geral','right'], ['antes8#5','bancos','wrong'], ['antes8#5','dinheiro','maybe'], ['antes8#5','aplicações financeiras','wrong'],
  ['base1#7','Contabilidade','right'], ['base1#7','a contabilidade','right'], ['base1#7','ciências contábeis','right'], ['base1#7','economia','wrong'], ['base1#7','administração','wrong'],
  ['base2#6','direitos','right'], ['base2#6','recebíveis','right'], ['base2#6','contas a receber','right'], ['base2#6','créditos','maybe'], ['base2#6','obrigações','wrong'], ['base2#6','dívidas','wrong'], ['base2#6','bens','wrong'],
  ['base2#7','obrigações','right'], ['base2#7','dívidas','right'], ['base2#7','exigibilidades','right'], ['base2#7','compromissos','right'], ['base2#7','passivo','maybe'], ['base2#7','direitos','wrong'], ['base2#7','receitas','wrong'],
  ['base3#7','patrimônio líquido','right'], ['base3#7','PL','right'], ['base3#7','capital próprio','right'], ['base3#7','ativo','wrong'], ['base3#7','passivo','wrong'], ['base3#7','lucro','wrong'],
  ['base4#6','prejuízo','right'], ['base4#6','déficit','right'], ['base4#6','resultado negativo','right'], ['base4#6','perda','maybe'], ['base4#6','lucro','wrong'], ['base4#6','superávit','wrong'], ['base4#6','saldo','wrong'], ['base4#6','despesa','wrong'],
  ['base5#4','analíticas','right'], ['base5#4','contas analíticas','right'], ['base5#4','contas de movimento','right'], ['base5#4','sintéticas','wrong'], ['base5#4','contas sintéticas','wrong'], ['base5#4','contas de resultado','wrong'],
  ['base6#5','competência','right'], ['base6#5','regime de competência','right'], ['base6#5','princípio da competência','right'], ['base6#5','caixa','wrong'], ['base6#5','regime de caixa','wrong'],
  ['basex1#3','entidade','right'], ['basex1#3','princípio da entidade','right'], ['basex1#3','autonomia patrimonial','right'], ['basex1#3','continuidade','wrong'], ['basex1#3','prudência','wrong'], ['basex1#3','competência','wrong'],
  ['basex3#4','relevância','right'], ['basex3#4','clareza','right'], ['basex3#4','confiabilidade','right'], ['basex3#4','comparabilidade','right'], ['basex3#4','materialidade','right'], ['basex3#4','lucratividade','wrong'], ['basex3#4','complexidade','wrong'], ['basex3#4','beleza','wrong'],
  ['dc1#8','débito','right'], ['dc1#8','devedor','right'], ['dc1#8','lado devedor','right'], ['dc1#8','crédito','wrong'], ['dc1#8','credor','wrong'], ['dc1#8','saldo','wrong'],
  ['dc2#6','débito','right'], ['dc2#6','a débito','right'], ['dc2#6','debitando','right'], ['dc2#6','crédito','wrong'], ['dc2#6','a crédito','wrong'],
  ['dc2#7','crédito','right'], ['dc2#7','a crédito','right'], ['dc2#7','débito','wrong'], ['dc2#7','devedor','wrong'],
  ['dc4#8','permutativo','right'], ['dc4#8','fato permutativo','right'], ['dc4#8','qualitativo','right'], ['dc4#8','modificativo','wrong'], ['dc4#8','misto','wrong'],
  ['dc5#4','estorno','right'], ['dc5#4','lançamento de estorno','right'], ['dc5#4','estornar','right'], ['dc5#4','retificação','maybe'], ['dc5#4','complementar','wrong'], ['dc5#4','transferência','wrong'],
  ['dc7#5','estorno','right'], ['dc7#5','um estorno','right'], ['dc7#5','ajuste','wrong'],
  ['lanc2#8','8','right'], ['lanc2#8','8%','right'], ['lanc2#8','oito por cento','right'], ['lanc2#8','11','wrong'], ['lanc2#8','9','wrong'],
  ['lanc7#5','1/12','right'], ['lanc7#5','um doze avos','right'], ['lanc7#5','1/2','wrong'], ['lanc7#5','1/13','wrong'],
  ['lanc5#7','diário','right'], ['lanc5#7','livro diário','right'], ['lanc5#7','o Diário','right'], ['lanc5#7','razão','wrong'], ['lanc5#7','livro razão','wrong'], ['lanc5#7','balancete','wrong'],
  ['imob4#4','impairment','right'], ['imob4#4','teste de impairment','right'], ['imob4#4','teste de recuperabilidade','right'], ['imob4#4','redução ao valor recuperável','right'], ['imob4#4','depreciação','wrong'], ['imob4#4','amortização','wrong'], ['imob4#4','inventário','wrong'],
  ['imobx3#4','exaustão','right'], ['imobx3#4','exaustao','right'], ['imobx3#4','depreciação','wrong'], ['imobx3#4','amortização','wrong'], ['imobx3#4','esgotamento','maybe'],
  ['estoq1#3','mercadorias','right'], ['estoq1#3','estoque de mercadorias','right'], ['estoq1#3','mercadorias para revenda','right'], ['estoq1#3','estoque','maybe'], ['estoq1#3','matéria-prima','wrong'], ['estoq1#3','produtos em elaboração','wrong'],
  ['estoq2#4','desconto incondicional','right'], ['estoq2#4','incondicional','right'], ['estoq2#4','desconto comercial','right'], ['estoq2#4','desconto condicional','wrong'], ['estoq2#4','condicional','wrong'], ['estoq2#4','desconto financeiro','wrong'], ['estoq2#4','abatimento','wrong'],
  ['estoq3#4','PEPS','right'], ['estoq3#4','FIFO','right'], ['estoq3#4','primeiro que entra primeiro que sai','right'], ['estoq3#4','UEPS','wrong'], ['estoq3#4','LIFO','wrong'], ['estoq3#4','custo médio','wrong'],
  ['estoq4#5','CMV','right'], ['estoq4#5','custo das mercadorias vendidas','right'], ['estoq4#5','CPV','wrong'], ['estoq4#5','DRE','wrong'],
  ['estoq5#2','inventário','right'], ['estoq5#2','inventário físico','right'], ['estoq5#2','contagem física','right'], ['estoq5#2','balanço de estoque','right'], ['estoq5#2','auditoria','wrong'], ['estoq5#2','conciliação','wrong'], ['estoq5#2','balancete','wrong'],
  ['estoq6#5','CPV','right'], ['estoq6#5','custo dos produtos vendidos','right'], ['estoq6#5','CMV','wrong'],
  ['estoq7#5','produtos em elaboração','right'], ['estoq7#5','em processo','right'], ['estoq7#5','produtos em processo','right'], ['estoq7#5','produtos acabados','wrong'], ['estoq7#5','matéria-prima','wrong'], ['estoq7#5','mercadorias','wrong'],
  ['demo1#6','data','right'], ['demo1#6','uma data','right'], ['demo1#6','data específica','right'], ['demo1#6','em uma data','right'], ['demo1#6','período','wrong'], ['demo1#6','um período','wrong'],
  ['demo2#8','lucro bruto','right'], ['demo2#8','resultado bruto','right'], ['demo2#8','margem bruta','maybe'], ['demo2#8','lucro líquido','wrong'], ['demo2#8','receita líquida','wrong'], ['demo2#8','lucro operacional','wrong'],
  ['demo3#5','DFC','right'], ['demo3#5','demonstração dos fluxos de caixa','right'], ['demo3#5','DRE','wrong'], ['demo3#5','DMPL','wrong'],
  ['demo5#5','DMPL','right'], ['demo5#5','demonstração das mutações do patrimônio líquido','right'], ['demo5#5','DLPA','wrong'], ['demo5#5','DRE','wrong'],
  ['cust1#5','custo','right'], ['cust1#5','é custo','right'], ['cust1#5','custo de produção','right'], ['cust1#5','despesa','wrong'], ['cust1#5','é despesa','wrong'],
  ['cust2#7','fixo','right'], ['cust2#7','custo fixo','right'], ['cust2#7','variável','wrong'], ['cust2#7','direto','wrong'], ['cust2#7','indireto','wrong'],
  ['cust3#7','contribuição','right'], ['cust3#7','margem de contribuição','right'], ['cust3#7','lucro','wrong'], ['cust3#7','segurança','wrong'],
  ['cust4#6','vendas','right'], ['cust4#6','orçamento de vendas','right'], ['cust4#6','receitas','maybe'], ['cust4#6','produção','wrong'], ['cust4#6','caixa','wrong'], ['cust4#6','despesas','wrong'],
  ['trib1#5','municipal','right'], ['trib1#5','prefeitura','right'], ['trib1#5','município','right'], ['trib1#5','esfera municipal','right'], ['trib1#5','estadual','wrong'], ['trib1#5','federal','wrong'], ['trib1#5','União','wrong'],
  ['trib2#6','DAS','right'], ['trib2#6','Documento de Arrecadação do Simples Nacional','right'], ['trib2#6','DARF','wrong'], ['trib2#6','GPS','wrong'],
  ['trib3#5','CBS','right'], ['trib3#5','contribuição sobre bens e serviços','right'], ['trib3#5','IBS','wrong'], ['trib3#5','ICMS','wrong'],
  ['trib3#6','IBS','right'], ['trib3#6','imposto sobre bens e serviços','right'], ['trib3#6','CBS','wrong'], ['trib3#6','ISS','wrong'],
  ['aud1#5','razoável','right'], ['aud1#5','segurança razoável','right'], ['aud1#5','absoluta','wrong'], ['aud1#5','total','wrong'], ['aud1#5','nenhuma','wrong'],
  ['aud2#6','detecção','right'], ['aud2#6','risco de detecção','right'], ['aud2#6','inerente','wrong'], ['aud2#6','controle','wrong'],
  ['aud3#5','funções','right'], ['aud3#5','segregação de funções','right'], ['aud3#5','tarefas','right'], ['aud3#5','atividades','right'], ['aud3#5','departamentos','wrong'], ['aud3#5','salários','wrong'],
  ['aud4#5','existência','right'], ['aud4#5','integridade','wrong'], ['aud4#5','valorização','wrong'],
  ['aud5#5','abstenção','right'], ['aud5#5','abstenção de opinião','right'], ['aud5#5','adversa','wrong'], ['aud5#5','opinião adversa','wrong'], ['aud5#5','com ressalva','wrong'],
  ['vida3#3','reserva de emergência','right'], ['vida3#3','fundo de emergência','right'], ['vida3#3','reserva para imprevistos','right'], ['vida3#3','reserva financeira','maybe'], ['vida3#3','investimento','wrong'], ['vida3#3','previdência','wrong'], ['vida3#3','seguro','wrong'],
  ['vida4#3','cesta','right'], ['vida4#3','cesto','right'], ['vida4#3','panela','wrong'], ['vida4#3','sacola','wrong'],
  ['fj5#1','inadimplência','right'], ['fj5#1','inadimplente','right'], ['fj5#1','calote','right'], ['fj5#1','falta de pagamento','right'], ['fj5#1','o cliente deu calote','right'], ['fj5#1','atraso','maybe'], ['fj5#1','adimplência','wrong'], ['fj5#1','pagamento em dia','wrong'], ['fj5#1','desconto','wrong'],
  ['fj6#3','juros de mora','right'], ['fj6#3','juros moratórios','right'], ['fj6#3','juros de atraso','right'], ['fj6#3','mora','maybe'], ['fj6#3','juros compostos','wrong'], ['fj6#3','multa','wrong'], ['fj6#3','juros simples','wrong'],
  ['fjb2#4','CNAB','right'], ['fjb2#4','cnab 240','right'], ['fjb2#4','DDA','wrong'], ['fjb2#4','Pix','wrong'],
  ['fj7#4','conciliação','right'], ['fj7#4','conciliação bancária','right'], ['fj7#4','conciliar','right'], ['fj7#4','conferência','maybe'], ['fj7#4','comparação','wrong'], ['fj7#4','auditoria','wrong'], ['fj7#4','balancete','wrong'],
  ['fj9#4','caixa','right'], ['fj9#4','regime de caixa','right'], ['fj9#4','competência','wrong'], ['fj9#4','regime de competência','wrong'],
  ['fjm1#1','PI','right'], ['fjm1#1','pedido de inserção','right'], ['fjm1#1','NF','wrong'], ['fjm1#1','contrato','wrong'],

  // ---------- explicações ----------
  ['antes5#6','Porque a empresa é uma pessoa diferente do dono, e se juntar tudo fica impossível saber se o negócio dá lucro.','right'],
  ['antes5#6','A empresa tem vida própria, independente do dono. Misturando as contas, os números ficam errados.','right'],
  ['antes5#6','Porque o dono pode gastar à vontade.','wrong'], ['antes5#6','Para pagar menos impostos.','wrong'],
  ['base1#8','Para anotar tudo o que acontece com o patrimônio e dar informações para os gestores decidirem.','right'],
  ['base1#8','Serve para controlar as finanças da empresa e ajudar na tomada de decisão.','right'],
  ['base1#8','Para pagar impostos.','wrong'], ['base1#8','Para fazer cálculos.','wrong'],
  ['base2#8','Bem é o que a empresa possui, como um carro. Direito é o que ela vai receber de outra pessoa, como uma venda a prazo.','right'],
  ['base2#8','Bem é coisa que a empresa tem; direito é valor que alguém deve pagar para a empresa.','right'],
  ['base2#8','Bem é bom e direito é certo.','wrong'], ['base2#8','São a mesma coisa.','wrong'],
  ['base3#9','Porque tudo que a empresa tem foi bancado por alguém: pelos credores, que é o passivo, ou pelos donos, que é o PL.','right'],
  ['base3#9','Os recursos vêm de dívidas com terceiros ou do capital dos sócios.','right'],
  ['base3#9','Porque é uma regra da contabilidade.','wrong'], ['base3#9','Porque o ativo é sempre maior.','wrong'],
  ['base4#8','É lançar receitas e despesas no mês em que ocorrem, não importa quando o dinheiro entra ou sai.','right'],
  ['base4#8','Registrar o fato quando acontece, independente do pagamento.','right'],
  ['base4#8','É a capacidade da empresa de competir no mercado.','wrong'],
  ['dc2#9','Porque a receita eleva o patrimônio líquido, e o PL cresce no lado credor.','right'],
  ['dc2#9','Receita gera lucro, que aumenta o PL; e o PL tem natureza credora.','right'],
  ['dc2#9','Porque entra dinheiro no caixa.','wrong'],
  ['lanc1#9','Um lançamento registra a receita da venda e o outro tira a mercadoria do estoque, levando o custo para o CMV.','right'],
  ['lanc1#9','Porque é preciso reconhecer o faturamento e também dar baixa no estoque pelo custo.','right'],
  ['lanc1#9','Porque o cliente paga em duas vezes.','wrong'], ['lanc1#9','Porque tem imposto.','wrong'],
  ['lanc4#8','Porque o bem perde valor com o uso, e esse custo é dividido ao longo da vida útil pela competência.','right'],
  ['lanc4#8','A máquina vai se desgastando e o custo dela é rateado ao longo dos anos.','right'],
  ['lanc4#8','Porque o governo manda.','wrong'], ['lanc4#8','Porque sai dinheiro do caixa todo mês.','wrong'],
  ['lanc6#5','Pela competência, o seguro vale por 12 meses, então a despesa é reconhecida mês a mês.','right'],
  ['lanc6#5','Porque ele cobre o ano inteiro; a despesa é apropriada aos poucos, um pouco em cada mês.','right'],
  ['lanc6#5','Porque foi pago à vista.','wrong'], ['lanc6#5','Porque em janeiro não tem despesa.','wrong'],
  ['demo1#8','Circulante vence ou vira dinheiro em até um ano; não circulante, depois de um ano.','right'],
  ['demo1#8','O circulante é de curto prazo, até 12 meses, e o não circulante é de longo prazo.','right'],
  ['demo1#8','Circulante é o dinheiro que circula na empresa.','wrong'],
  ['demo3#7','Porque ela vendeu fiado e ainda não recebeu, ou usou o dinheiro para comprar estoque.','right'],
  ['demo3#7','O lucro é por competência; o dinheiro das vendas parceladas só entra depois.','right'],
  ['demo3#7','Porque o lucro é pequeno.','wrong'], ['demo3#7','Porque tem muitos impostos.','wrong'],
  ['demo4#8','Que o ativo circulante não cobre o passivo circulante: faltam recursos para pagar as contas de curto prazo.','right'],
  ['demo4#8','A empresa deve mais no curto prazo do que tem para pagar e pode passar aperto.','right'],
  ['demo4#8','Que a empresa está lucrando.','wrong'], ['demo4#8','Que a empresa tem muito dinheiro sobrando.','wrong'],
  ['cust1#6','Custo é o gasto para fabricar o produto; despesa é o gasto para vender e administrar.','right'],
  ['cust1#6','Custo vai para a produção; despesa é do escritório e das vendas.','right'],
  ['cust1#6','Custo é caro e despesa é barato.','wrong'],
  ['cust3#8','É quando a receita paga todos os custos e despesas e a empresa não tem lucro nem prejuízo.','right'],
  ['cust3#8','O volume de vendas em que a empresa empata: o lucro é igual a zero.','right'],
  ['cust3#8','É quando a empresa tem o maior lucro.','wrong'], ['cust3#8','É o preço de venda.','wrong'],
  ['trib1#6','O imposto não está ligado a nenhum serviço específico; a taxa é cobrada por um serviço público prestado, como a emissão de um alvará.','right'],
  ['trib1#6','Imposto o governo cobra sem dar nada em troca diretamente; taxa é paga quando você usa um serviço público.','right'],
  ['trib1#6','Imposto é caro e taxa é barata.','wrong'], ['trib1#6','São a mesma coisa.','wrong'],
  ['aud1#6','Para que a opinião dele tenha credibilidade e seja imparcial, sem conflito de interesses.','right'],
  ['aud1#6','Para que ninguém duvide do parecer: ele não pode ter vínculo com a empresa auditada.','right'],
  ['aud1#6','Para ganhar mais.','wrong'], ['aud1#6','Para trabalhar sozinho.','wrong'],
  ['aud3#6','O preventivo impede que o erro aconteça; o detectivo descobre o erro depois que ele aconteceu.','right'],
  ['aud3#6','Preventivo age antes, como uma senha; detectivo identifica o problema depois, como uma conciliação.','right'],
  ['aud3#6','Nenhuma diferença.','wrong'],
  ['vida1#4','É tudo o que a pessoa tem menos tudo o que ela deve.','right'],
  ['vida1#4','Os bens e investimentos, descontadas as dívidas.','right'],
  ['vida1#4','É o salário da pessoa.','wrong'], ['vida1#4','É o dinheiro na conta.','wrong'],
  ['vida3#4','Para ter dinheiro em caso de imprevistos, como perder o emprego, sem precisar pegar empréstimo.','right'],
  ['vida3#4','Para não depender de crédito caro quando surgir um problema inesperado.','right'],
  ['vida3#4','Para viajar nas férias.','wrong'], ['vida3#4','Para investir na bolsa.','wrong'],
  ['fj15#3','É conferir o extrato com o que foi lançado no sistema, achar as diferenças e acertar.','right'],
  ['fj15#3','Confrontar a movimentação do banco com os registros da empresa e corrigir o que não bate.','right'],
  ['fj15#3','Checar se os lançamentos do ERP batem com o banco e regularizar as divergências.','right'],
  ['fj15#3','É calcular o lucro da empresa no mês.','wrong'], ['fj15#3','É pagar as contas pelo banco.','wrong'],
  ['fj15#5','Porque vendeu a prazo e ainda vai receber, e usou dinheiro para pagar dívidas e comprar estoque.','right'],
  ['fj15#5','O lucro é reconhecido na venda, mas o cliente paga depois; e compras de máquinas saem do caixa sem ser despesa.','right'],
  ['fj15#5','Porque a empresa não vendeu nada.','wrong'], ['fj15#5','Porque o lucro é mentira.','wrong']
];

/* Respostas erradas que o corretor por palavras-chave aceita (papéis trocados, oposto do
   assunto). A IA recusa estas mesmo assim: são as únicas situações em que ela rebaixa. */
export const KNOWN_KEYWORD_LEAKS = [
  ['base4#8','É registrar só quando o dinheiro entra ou sai do caixa.'],
  ['dc2#9','Porque a receita tem natureza devedora e aumenta o patrimônio.'],
  ['demo1#8','Circulante é de longo prazo e não circulante é de curto prazo.'],
  ['cust1#6','Custo é o gasto com vendas e despesa é o gasto da fábrica.'],
  ['aud3#6','O preventivo encontra os erros depois e o detectivo evita antes.']
];

/* Tentativas de enganar o corretor: chutes com duas opções, negações e opostos. */
export const ADVERSARIAL = [
  ['base2#6','direitos e obrigações'], ['cust2#7','fixo ou variável'], ['aud1#5','razoável ou absoluta'], ['estoq3#4','peps ou ueps'],
  ['demo3#5','DFC ou DRE'], ['trib1#5','municipal/estadual'], ['estoq4#5','CMV/CPV'], ['dc1#8','débito não, crédito'], ['dc1#8','crédito, não débito'],
  ['fj6#3','juros de mora não, multa'], ['antes6#6','prazo não, à vista'], ['base3#7','não é patrimônio líquido'], ['aud1#5','razoável não, absoluta'],
  ['vida3#3','reserva de lucros'], ['vida3#3','reserva legal'], ['fj5#1','atraso do fornecedor'], ['base4#6','perda de lucro'], ['fj5#1','adimplência'],
  ['estoq2#4','desconto condicional'], ['dc2#9','Porque a receita diminui o PL e o PL é devedor.'], ['cust3#8','É quando a empresa tem prejuízo e não cobre os custos.'],
  ['cust1#6','Custo é caro e despesa é barato.'], ['fj15#3','É calcular o lucro da empresa no mês.']
];
