/* Segundo conjunto, escrito sem olhar a base de conhecimento: palavras de aluno,
   sem acento, com erro de digitação e jeitos informais. Mede o que a IA generaliza. */
export const HOLDOUT = [
  ['fj5#1','calote do cliente','right'], ['fj5#1','clientes inadimplentes','right'], ['fj5#1','inadiplência','right'], ['fj5#1','o cliente ficou devendo','maybe'], ['fj5#1','adimplente','wrong'], ['fj5#1','juros','wrong'],
  ['antes3#6','saldo bancário','right'], ['antes3#6','saudo','right'], ['antes3#6','sobra','maybe'], ['antes3#6','balanço','wrong'],
  ['base4#6','deficit','right'], ['base4#6','prejuizo','right'], ['base4#6','resultado deficitário','right'], ['base4#6','lucro negativo','right'], ['base4#6','receita','wrong'],
  ['vida3#3','reserva de emergencia','right'], ['vida3#3','fundo de reserva','maybe'], ['vida3#3','colchão de segurança','right'], ['vida3#3','poupança para emergências','right'], ['vida3#3','cartão de crédito','wrong'],
  ['fj6#3','juros moratorios','right'], ['fj6#3','juros de mora diários','right'], ['fj6#3','encargos de mora','maybe'], ['fj6#3','correção monetária','wrong'],
  ['fj7#4','conciliação de contas','right'], ['fj7#4','batimento bancário','maybe'], ['fj7#4','reconciliação','right'], ['fj7#4','auditoria interna','wrong'],
  ['demo1#6','numa data','right'], ['demo1#6','em um dia específico','maybe'], ['demo1#6','ponto no tempo','maybe'], ['demo1#6','no período','wrong'],
  ['cust1#5','é um custo','right'], ['cust1#5','custo de fabricação','right'], ['cust1#5','gasto de produção','right'], ['cust1#5','despesa operacional','wrong'],
  ['trib1#5','é municipal','right'], ['trib1#5','da prefeitura','right'], ['trib1#5','municipio','right'], ['trib1#5','governo municipal','right'], ['trib1#5','cidade','maybe'], ['trib1#5','governo federal','wrong'],
  ['aud1#5','razoavel','right'], ['aud1#5','absoluta não, razoável','right'], ['aud1#5','segurança total','wrong'],
  ['dc2#6','debito','right'], ['dc2#6','lado esquerdo','right'], ['dc2#6','lado direito','wrong'],
  ['estoq3#4','primeiro que entra, primeiro que sai','right'], ['estoq3#4','PEPS (FIFO)','right'], ['estoq3#4','último que entra primeiro que sai','wrong'],
  ['fjb2#4','cnab240','right'], ['fjb2#4','boleto','wrong'],
  ['lanc5#7','livro diario','right'], ['lanc5#7','diário geral','right'], ['lanc5#7','razão analítico','wrong'],
  ['base2#7','passivos','maybe'], ['base2#7','débitos','maybe'], ['base2#7','créditos','wrong'],
  ['base6#5','regime de competencia','right'], ['base6#5','regime caixa','wrong'],
  ['estoq5#2','contagem do estoque','right'], ['estoq5#2','levantamento físico','maybe'], ['estoq5#2','conferência de notas','wrong'],
  ['fj15#3','Bater o extrato com o razão da empresa, ver o que ficou sem par e fazer os acertos.','right'],
  ['fj15#3','Pegar o relatório do banco, comparar linha a linha com o que a contabilidade registrou e resolver as divergências.','right'],
  ['fj15#3','Checar movimentação do banco contra os lançamentos internos e acertar o que estiver faltando.','right'],
  ['fj15#3','Conciliação é quando o banco aprova um empréstimo.','wrong'], ['fj15#3','Comparar preços de fornecedores.','wrong'],
  ['base4#8','Contabilizar pelo fato gerador, e não pela data do pagamento ou recebimento.','right'],
  ['base4#8','As receitas e despesas entram no mês em que acontecem, mesmo que o dinheiro só entre depois.','right'],
  ['vida1#4','Soma dos bens menos as dívidas.','right'], ['vida1#4','Patrimônio líquido é ativos menos passivos da pessoa.','right'],
  ['cust3#8','É o ponto em que a empresa não ganha nem perde dinheiro.','right'],
  ['demo3#7','Porque as vendas foram parceladas e o dinheiro ainda não entrou.','right'],
  ['lanc4#8','O equipamento vai perdendo valor com o tempo, então parte do custo vira despesa todo ano.','right'],
  ['aud3#6','Preventivo bloqueia o erro antes; detectivo aponta o erro depois.','right'],
  ['trib1#6','Imposto é geral, não tem retorno específico; taxa é cobrada por um serviço prestado.','right'],
  ['base1#8','Para gerar relatórios que ajudam o dono a tomar decisões sobre o negócio.','right'],
  ['base3#9','Porque cada real do ativo tem uma fonte: dinheiro dos donos ou de terceiros.','right'],
  ['dc2#9','Receita eleva o PL e contas de PL crescem pelo lado direito.','right'],
  ['lanc6#5','Porque o seguro é usado ao longo do ano; por competência, a despesa é lançada em doze parcelas mensais.','right'],
  ['demo4#8','Que o passivo de curto prazo supera o ativo circulante, sinal de aperto no caixa.','right'],
  ['antes5#6','Para não confundir as finanças pessoais com as da empresa e saber se ela lucra.','right'],
  ['antes5#6','Porque o dono é o chefe.','wrong'],
  ['vida3#4','Pra não ter que usar o cheque especial se acontecer algo inesperado.','right'],
  ['fj15#5','Porque o lucro aparece quando vende, mas o cliente pode pagar só daqui a 60 dias.','right'],
  ['fj15#5','Porque o contador errou.','wrong'],
  ['cust1#6','Custo entra no produto, como matéria-prima; despesa é o que a empresa gasta para funcionar, como o aluguel do escritório.','right'],
  ['demo1#8','Circulante é o que vira dinheiro ou vence logo, dentro de um ano; o resto é não circulante.','right'],
  ['aud1#6','Porque se ele for amigo do dono, o parecer não vale nada.','right'],
  ['lanc1#9','Porque tem a venda em si e tem a saída da mercadoria do estoque.','right']
];
