/* Glossário de termos contábeis (busca livre na tela de Glossário). */

export const GLOSSARY = [
 ["Ativo","Bens e direitos controlados pela empresa, que devem gerar benefícios futuros."],
 ["Passivo","Obrigações da empresa com terceiros: fornecedores, empréstimos, salários, impostos."],
 ["Patrimônio Líquido (PL)","Diferença entre Ativo e Passivo; a parte que pertence aos sócios."],
 ["Débito","Lado esquerdo de uma conta. Aumenta Ativo e Despesa; diminui Passivo, PL e Receita."],
 ["Crédito","Lado direito de uma conta. Aumenta Passivo, PL e Receita; diminui Ativo e Despesa."],
 ["Razonete","Representação de uma conta em forma de T, com débitos à esquerda e créditos à direita."],
 ["Partidas dobradas","Método em que todo fato tem pelo menos um débito e um crédito de igual valor."],
 ["Balancete de verificação","Lista das contas com seus saldos, para conferir se devedores e credores se igualam."],
 ["Livro Diário","Registro de todos os lançamentos em ordem cronológica."],
 ["Livro Razão","Registro dos lançamentos agrupados por conta, com o saldo de cada uma."],
 ["Regime de competência","Receitas e despesas são reconhecidas quando ocorrem, independente do pagamento."],
 ["Regime de caixa","Receitas e despesas reconhecidas apenas quando o dinheiro entra ou sai."],
 ["Receita","Aumento de benefícios econômicos gerado pela atividade, que aumenta o PL."],
 ["Despesa","Consumo de recursos para gerar receitas ou administrar, que diminui o PL."],
 ["Custo","Gasto relacionado à produção de bens ou à prestação de serviços."],
 ["CMV","Custo das Mercadorias Vendidas: EI + Compras − EF, no inventário periódico."],
 ["PEPS","Primeiro que entra, primeiro que sai: método de custeio de estoques."],
 ["Depreciação","Distribuição do custo de um bem tangível ao longo de sua vida útil."],
 ["Amortização","Distribuição do custo de um intangível com vida útil definida."],
 ["Exaustão","Distribuição do custo de recursos naturais, como minas e florestas."],
 ["Imobilizado","Bens tangíveis usados na operação por mais de um ano: máquinas, veículos, prédios."],
 ["Intangível","Bens sem corpo físico: marcas, softwares, patentes."],
 ["Circulante","Itens que se realizam ou vencem em até 12 meses (ou no ciclo operacional)."],
 ["Não Circulante","Itens que se realizam ou vencem após 12 meses."],
 ["Balanço Patrimonial","Demonstração da posição de Ativo, Passivo e PL em uma data."],
 ["DRE","Demonstração do Resultado do Exercício: mostra como se formou o lucro ou prejuízo."],
 ["DFC","Demonstração dos Fluxos de Caixa: entradas e saídas de dinheiro por atividade."],
 ["EBITDA","Lucro antes de juros, impostos, depreciação e amortização."],
 ["Liquidez corrente","Ativo Circulante ÷ Passivo Circulante."],
 ["ROE","Retorno sobre o Patrimônio Líquido: Lucro líquido ÷ PL."],
 ["Margem de contribuição","Preço menos custos e despesas variáveis; o que sobra para cobrir os fixos."],
 ["Ponto de equilíbrio","Volume de vendas em que o lucro é zero: Custos fixos ÷ MC unitária."],
 ["Capital social","Recursos que os sócios entregaram ou se comprometeram a entregar à empresa."],
 ["Reservas de lucros","Parcela do lucro retida no PL para finalidades específicas."],
 ["Fornecedores","Obrigação por compras a prazo de mercadorias e serviços."],
 ["Clientes","Direito a receber por vendas a prazo; também chamado de Contas a receber."],
 ["CPC","Comitê de Pronunciamentos Contábeis, que elabora as normas contábeis brasileiras."],
 ["IFRS","Normas internacionais de contabilidade, base das normas brasileiras."],
 ["SPED","Sistema Público de Escrituração Digital, que recebe a ECD e outras obrigações."],
 ["Simples Nacional","Regime para micro e pequenas empresas, com guia única (DAS)."],
 ["Lucro Presumido","Regime em que o lucro tributável é um percentual da receita."],
 ["Lucro Real","Regime em que o imposto incide sobre o lucro contábil ajustado."],
 ["Não cumulatividade","Sistema em que o tributo das compras é abatido do tributo das vendas."],
 ["CBS","Contribuição sobre Bens e Serviços, federal, que substitui PIS e Cofins."],
 ["IBS","Imposto sobre Bens e Serviços, de estados e municípios, que substitui ICMS e ISS."],
 ["Materialidade","Valor a partir do qual um erro poderia influenciar decisões dos usuários."],
 ["Risco de auditoria","Risco de o auditor emitir opinião inadequada sobre as demonstrações."],
 ["Ceticismo profissional","Postura de questionar e avaliar criticamente as evidências."],
 ["Controle interno","Processos para proteger ativos e garantir informações confiáveis."],
 ["Segregação de funções","Separar autorizar, registrar e custodiar entre pessoas diferentes."],
 ["Asserções","Afirmações implícitas nas demonstrações testadas pelo auditor: existência, integridade etc."],
 ["Opinião com ressalva","Opinião emitida quando há distorção relevante, mas não generalizada."]
];

export const GLOSS_ADD = [
 ["Porcentagem","Parte de cada cem. 25% = 25 ÷ 100 = 0,25."],
 ["Juros compostos","Juros calculados sobre o montante acumulado: juros sobre juros."],
 ["Montante","Capital somado aos juros."],
 ["Rateio","Divisão proporcional de um valor entre partes, como setores ou produtos."],
 ["CNPJ","Cadastro Nacional da Pessoa Jurídica: o número de registro da empresa."],
 ["MEI","Microempreendedor Individual, com faturamento de até R$ 81 mil por ano."],
 ["Duplicata","Título de crédito originado de uma venda a prazo."],
 ["Nota fiscal","Documento que comprova a venda de bens ou serviços e destaca os tributos."],
 ["Disponível","Caixa, bancos e aplicações de liquidez imediata."],
 ["Estorno","Lançamento inverso usado para anular um lançamento errado."],
 ["Despesa antecipada","Gasto pago antes do uso, registrado no Ativo e apropriado ao longo do tempo."],
 ["Provisão","Obrigação existente com valor ou prazo incertos, como férias e 13º."],
 ["DMPL","Demonstração das Mutações do Patrimônio Líquido."],
 ["DVA","Demonstração do Valor Adicionado: riqueza gerada e sua distribuição."],
 ["Notas explicativas","Informações que detalham e explicam as demonstrações financeiras."],
 ["Plano de contas","Lista organizada e codificada das contas usadas pela empresa."],
 ["Conta analítica","Conta de último nível, que recebe lançamentos."],
 ["Reserva de emergência","Dinheiro guardado para imprevistos, em aplicação de fácil resgate."]
];
