/* Base de conhecimento do corretor inteligente (src/engine/ai/).
   CONCEPTS: cada conceito lista jeitos equivalentes de dizer a mesma coisa. Plural,
   feminino e formas do mesmo verbo são reconhecidos pelo radical; escreva aqui só as
   variações que o radical não pega. Um "~" na frente marca um termo aproximado: a IA
   sugere aceitar, mas não aceita sozinha.
   OPPOSITES: pares que nunca podem ser trocados numa resposta. */

/* Termos técnicos: podem ser a resposta de uma questão. */
export const TERM_CONCEPTS = {
  cem:['cem','cento','100'],
  regra_tres:['regra de três','regra de 3','regra de três simples','~proporção'],
  saldo:['saldo','saldo final','saldo da conta','saldo líquido'],
  montante:['montante','valor futuro','montante final','valor com juros','capital mais juros','~total'],
  ponderada:['ponderada','média ponderada','~média com pesos'],
  cnpj:['cnpj','cadastro nacional da pessoa jurídica','cadastro nacional de pessoa jurídica','cadastro nacional de pessoas jurídicas'],
  a_prazo:['prazo','a prazo','aprazo','fiado','parcelado','pagamento futuro','~crediário','parcelamento','compra a crédito','venda a crédito','comprar a crédito','daqui a','pagar depois','paga depois','receber depois','recebe depois','dias depois','no futuro','mais tarde'],
  a_vista:['à vista','avista','pagamento imediato','pagar na hora'],
  nota_fiscal:['nota fiscal','nf','nfe','nf e','nota fiscal eletrônica','danfe','~cupom fiscal','~nfc e','~nota'],
  caixa:['caixa','conta caixa','caixa geral','regime de caixa'],
  contabilidade:['contabilidade','ciência contábil','ciências contábeis','contábil'],
  direitos:['direitos','direito','créditos a receber','valores a receber','contas a receber','recebíveis','haveres','~créditos'],
  obrigacoes:['obrigações','obrigação','dívidas','dívida','exigibilidades','compromissos','contas a pagar','passivo exigível','~passivo','~pendências'],
  patrimonio_liquido:['patrimônio líquido','pl','capital próprio','recursos próprios','situação líquida'],
  lucro:['lucro','superávit','resultado positivo','ganho','lucro líquido'],
  prejuizo:['prejuízo','déficit','resultado negativo','lucro negativo','prejuízo líquido','~perda','~desequilíbrio','deficitário','resultado deficitário'],
  analiticas:['analíticas','analítica','contas analíticas','contas de movimento','contas de lançamento'],
  sinteticas:['sintéticas','sintética','contas sintéticas','contas de grupo'],
  competencia:['competência','regime de competência','princípio da competência','fato gerador'],
  entidade:['entidade','princípio da entidade','autonomia patrimonial','~separação patrimonial'],
  relevancia:['relevância','relevante','materialidade','pertinência','~importância'],
  fidedigna:['representação fidedigna','fidedigna','fidedignidade','confiabilidade','neutralidade','completude','livre de erro','veracidade','fiabilidade','autenticidade','~precisão'],
  comparabilidade:['comparabilidade','comparável'],
  verificabilidade:['verificabilidade','verificável'],
  tempestividade:['tempestividade','tempestiva','informação no tempo certo'],
  compreensibilidade:['compreensibilidade','compreensível','clareza','clara','compreensão','~simplicidade'],
  debito:['débito','debitar','lado devedor','devedor','lado esquerdo','natureza devedora'],
  credito:['crédito','creditar','lado credor','credor','lado direito','natureza credora'],
  permutativo:['permutativo','fato permutativo','qualitativo','fato qualitativo'],
  modificativo:['modificativo','fato modificativo','quantitativo'],
  estorno:['estorno','estornar','lançamento de estorno','~retificação','~cancelamento'],
  doze_avos:['1/12','um doze avos','doze avos','um doze avo'],
  diario:['diário','livro diário'],
  razao:['razão','livro razão'],
  impairment:['impairment','teste de impairment','valor recuperável','teste de valor recuperável','redução ao valor recuperável','teste de recuperabilidade','recuperabilidade'],
  exaustao:['exaustão','~esgotamento'],
  amortizacao:['amortização','amortizar'],
  depreciacao:['depreciação','depreciar','desgaste','desvalorização'],
  mercadorias:['mercadorias','mercadoria','estoque de mercadorias','mercadorias para revenda','estoque para revenda','~estoque','produtos para revenda','produtos prontos para venda','~produtos'],
  desconto_incondicional:['incondicional','desconto incondicional','desconto comercial','desconto na nota'],
  desconto_condicional:['condicional','desconto condicional','desconto financeiro','desconto por pagamento antecipado'],
  peps:['peps','fifo','primeiro que entra primeiro que sai','primeiro a entrar primeiro a sair'],
  ueps:['ueps','lifo','último que entra primeiro que sai'],
  custo_medio:['custo médio','média ponderada móvel','custo médio ponderado'],
  cmv:['cmv','custo das mercadorias vendidas','custo da mercadoria vendida','custo das vendas'],
  cpv:['cpv','custo dos produtos vendidos','custo do produto vendido'],
  inventario:['inventário','inventário físico','contagem física','contagem do estoque','contagem de estoque','balanço de estoque','~contagem','~balanço'],
  em_elaboracao:['produtos em elaboração','em elaboração','produtos em processo','produção em andamento','estoque em processo','em processo','em fabricação'],
  data:['data','uma data','data específica','data determinada','momento específico','instante','~momento'],
  periodo:['período','intervalo de tempo','exercício','~mês'],
  lucro_bruto:['lucro bruto','resultado bruto','~margem bruta'],
  dfc:['dfc','demonstração dos fluxos de caixa','demonstração do fluxo de caixa','fluxo de caixa'],
  dmpl:['dmpl','demonstração das mutações do patrimônio líquido','mutações do patrimônio líquido'],
  dre:['dre','demonstração do resultado','demonstração do resultado do exercício'],
  custo:['custo','custos','custo de produção','gasto de produção'],
  despesa:['despesa','despesas','gasto administrativo','gasto com vendas'],
  fixo:['fixo','fixos','custo fixo','custos fixos'],
  variavel:['variável','variáveis','custo variável','custos variáveis'],
  contribuicao:['contribuição','margem de contribuição'],
  vendas:['vendas','venda','orçamento de vendas','previsão de vendas','~orçamento de receitas','~receitas','~faturamento'],
  municipal:['municipal','município','municípios','prefeitura','prefeituras','municipalidade','esfera municipal'],
  estadual:['estadual','estado','estados','esfera estadual'],
  federal:['federal','união','governo federal','esfera federal'],
  das:['das','documento de arrecadação do simples nacional','documento de arrecadação do simples','guia do simples'],
  cbs:['cbs','contribuição sobre bens e serviços'],
  ibs:['ibs','imposto sobre bens e serviços'],
  razoavel:['razoável','segurança razoável','asseguração razoável','alto nível de segurança'],
  absoluta:['absoluta','segurança absoluta','segurança total','garantia total'],
  deteccao:['detecção','risco de detecção','detectar'],
  funcoes:['funções','função','tarefas','atividades','responsabilidades','deveres','atribuições'],
  existencia:['existência','existe','existir'],
  abstencao:['abstenção','abstenção de opinião','negativa de opinião','~abster'],
  reserva_emergencia:['reserva de emergência','fundo de emergência','reserva para emergências','reserva para imprevistos','poupança de emergência','colchão financeiro','~reserva financeira','~reserva','colchão de segurança','colchão','reserva de segurança','dinheiro guardado para emergências'],
  cesta:['cesta','cesto'],
  inadimplencia:['inadimplência','inadimplente','inadimplemento','calote','falta de pagamento','atraso no pagamento','atraso de pagamento','não pagamento','cliente em atraso','devedor em atraso','~atraso','~atrasado','~devedor','~descumprimento','~insolvência'],
  juros_mora:['juros de mora','juros moratórios','juros por atraso','juros de atraso','juros pelo atraso','juros do atraso','~mora'],
  multa:['multa','penalidade','~penalização'],
  cnab:['cnab','padrão cnab','cnab 240','cnab 400'],
  conciliacao:['conciliação','conciliação bancária','conciliar','conciliação de extrato','~batimento','~conferência bancária','~conferência','reconciliação','reconciliação bancária'],
  pi:['pi','pedido de inserção','~autorização de veiculação','~ordem de inserção']
};

/* Vocabulário das explicações: verbos e ideias gerais. */
export const IDEA_CONCEPTS = {
  separado:['separado','separar','separação','distinto','distinta','independente','à parte','apartado','autonomia','não misturar','outra pessoa','pessoa diferente','diferente do dono','não confundir','não juntar','separadas','cada um no seu','não é a mesma pessoa','pessoa jurídica diferente'],
  misturar:['misturar','mistura','confundir','confusão','bagunçar','bagunça','juntar'],
  distorcer:['distorcer','distorção','atrapalhar','prejudicar','errado','erro','incorreto','impreciso','não saber','sem saber','dificultar','comprometer','confundir os números'],
  registrar:['registrar','registro','anotar','escriturar','escrituração','lançar','contabilizar','documentar'],
  informar:['informação','informar','dados','relatório','relatórios','demonstrações','números','controle','controlar','organizar','organização','medir','mensurar'],
  decidir:['decidir','decisão','decisões','escolher','escolha','gestão','gerir','administrar','planejar','planejamento','orientar','deliberar','tomada de decisão'],
  patrimonio:['patrimônio','bens','riqueza','recursos','finanças','dinheiro da empresa'],
  possuir:['possuir','possui','ter','tem','propriedade','pertence','pertencer','próprio'],
  receber:['receber','recebimento','a receber','entrar','entrada','cobrar','cobrança','vai receber'],
  pagar:['pagar','pagamento','quitar','quitação','liquidar','sair','saída','desembolso','desembolsar','gastar','gasto'],
  terceiros:['terceiros','outras pessoas','outros','alguém','outra empresa','clientes','cliente'],
  origem:['origem','fonte','veio','vem','de onde','financiado','financiamento','captado','obtido','proveniente','originado','provém','provenientes','originária'],
  socios:['sócios','sócio','donos','dono','proprietários','proprietário','acionistas','capital dos sócios','capital social','investidores','fundadores'],
  emprestimo:['empréstimo','empréstimos','financiamento','financiamentos','dívida bancária','crédito bancário'],
  acontecer:['acontecer','acontece','ocorrer','ocorre','ocorrência','realizar','realização','fato','quando o fato acontece'],
  independente_de:['independentemente','independente','não importa','não depende','tanto faz','sem depender','seja quando for'],
  aumentar:['aumentar','aumento','elevar','crescer','cresce','somar','acrescentar','subir','sobe','acrescer'],
  diminuir:['diminuir','diminuição','reduzir','redução','cair','cai','baixar','descer','abater','subtrair','decrescer'],
  natureza:['natureza','lado','saldo natural'],
  preco_venda:['preço de venda','preço','valor de venda','faturamento','faturar'],
  baixa_estoque:['baixa','baixa no estoque','dar baixa','sai do estoque','saída do estoque','tirar do estoque'],
  desgaste:['desgastar','desgaste','perder valor','perde valor','perda de valor','envelhecer','envelhece','obsolescência','obsoleto','estragar','uso','usado','vida útil','deterioração','desvalorização','deteriorar','desvalorizar'],
  distribuir:['distribuir','distribuição','ratear','rateio','repartir','dividir','espalhar','alocar','aos poucos','ao longo','ao longo do tempo','parcelado','proporcional','mês a mês','cada mês','mensalmente','apropriar','apropriação'],
  doze_meses:['12 meses','doze meses','um ano','1 ano','ano','exercício seguinte','próximo exercício'],
  curto_prazo:['curto prazo','curto','menos de um ano','até um ano','até 12 meses','próximos meses','em breve','rápido','logo','dentro de um ano','em até um ano','no máximo um ano','nos próximos 12 meses','próximo ano'],
  longo_prazo:['longo prazo','longo','mais de um ano','acima de um ano','depois de 12 meses','mais de 12 meses','após um ano','passa de 12 meses','passa de um ano','acima de 12 meses','o resto'],
  insuficiente:['insuficiente','não basta','não bastam','não dá','não cobre','falta','faltar','faltam','dificuldade','aperto','sufoco','não consegue pagar','sem dinheiro','carência','~ausência'],
  producao:['produção','produzir','fabricar','fabricação','fábrica','industrial','indústria','fazer o produto','manufatura','montagem'],
  vender_administrar:['vender','administrar','administração','administrativo','escritório','comercial','comercialização','marketing','propaganda','gestão da empresa'],
  lucro_zero:['lucro zero','sem lucro','nem lucro nem prejuízo','lucro nem prejuízo','não tem lucro nem prejuízo','não teve lucro nem prejuízo','não dá lucro nem prejuízo','não tem lucro e nem prejuízo','lucro igual a zero','lucro é zero','sem lucro e sem prejuízo','empate','empatar','resultado nulo','zero a zero','não ganha nem perde'],
  cobrir:['cobrir','cobre','igualar','iguala','empatar','suficiente para pagar'],
  contrapartida:['contrapartida','retorno direto','troca','em troca'],
  sem_contrapartida:['sem contrapartida','sem uma contrapartida','não tem contrapartida','sem nada em troca','sem dar nada em troca','não dá nada em troca','nada em troca','sem retorno direto','não está ligado','não é ligado','não está vinculado','não é vinculado','não vinculado','sem vínculo','não depende de serviço','independe de serviço','sem serviço específico','não tem serviço específico','geral','para todos'],
  servico_especifico:['serviço específico','serviço público','fiscalização','poder de polícia','alvará','licença','coleta de lixo','emissão de documento'],
  confiavel:['confiável','confiança','credibilidade','crível','ninguém duvide','ninguém duvidar','não duvidem','sem dúvida','acreditar','acreditem','confiem','imparcial','imparcialidade','isento','isenção','neutro','neutralidade','objetivo','objetividade','verdadeiro','justo','veracidade','honestidade','transparência'],
  conflito:['conflito','conflito de interesse','conflitos de interesse','interesse','vínculo','influência','influenciar','relação','ligação','parentesco','amizade','dependência','amigo','amizade','parente','amigo do dono','parente do dono'],
  evitar:['evitar','prevenir','impedir','bloquear','barrar','antecipar','previne','evita','inibir','~minimizar'],
  detectar:['detectar','encontrar','identificar','descobrir','achar','perceber','localizar','apontar','diagnosticar','constatar','flagrar'],
  antes:['antes','antecipadamente','previamente','de antemão'],
  depois:['depois','após','posteriormente','em seguida','mais tarde','quando já aconteceu'],
  diferenca:['diferença','diferenças','divergência','discrepância','inconsistência','desencontro','sem par','item sem par','não bate','não batem','disparidade'],
  investigar:['investigar','investigação','apurar','averiguar','analisar','análise','examinar','procurar','buscar','entender a causa','descobrir o motivo'],
  comparar:['comparar','comparação','confrontar','confronto','conferir','conferência','checar','cruzar','verificar se bate','bater','batimento'],
  ajustar:['ajustar','ajuste','corrigir','correção','acertar','acerto','regularizar','lançar a diferença','igualar','bater os saldos','fechar'],
  extrato:['extrato','extrato bancário','extrato do banco','movimento do banco','banco','conta bancária'],
  sistema:['sistema','erp','contabilidade da empresa','controle interno','lançamentos','livros','razão da empresa','software','programa','~planilha'],
  imprevisto:['imprevisto','imprevistos','emergência','emergências','inesperado','inesperada','urgência','problema','desemprego','perder o emprego','doença','saúde','conserto','acidente','contingência','contratempo','contratempos','eventualidade','imprevisível','imprevisíveis'],
  endividar:['endividar','endividamento','dívida','dívidas','empréstimo','juros','juros altos','cartão','cheque especial','crediário','crédito caro','pegar crédito','dinheiro emprestado','emprestado','pedir emprestado'],
  diferenca_de:['menos','subtrair','subtração','diferença entre','tirando','descontando','sobra','sobrar','o que resta','restante'],
  dever:['deve','dever','devido','dívidas','dívida','obrigações','passivo'],
  investimento:['investimento','investimentos','investir','aplicação','aplicações','máquinas','equipamentos','bens'],
  estoque:['estoque','estoques','mercadoria','mercadorias','compras de estoque','comprar estoque'],
  compra:['compra','compras','comprar','adquirir','aquisição']
};

export const CONCEPTS = { ...TERM_CONCEPTS, ...IDEA_CONCEPTS };

/* Pares que não podem ser confundidos. Se a resposta de referência usa um lado e a
   pessoa escreve o outro (sem o primeiro), a IA não aceita. */
export const OPPOSITES = [
  ['debito','credito'], ['lucro','prejuizo'], ['a_prazo','a_vista'], ['curto_prazo','longo_prazo'],
  ['fixo','variavel'], ['custo','despesa'], ['competencia','caixa'], ['razoavel','absoluta'],
  ['analiticas','sinteticas'], ['permutativo','modificativo'], ['peps','ueps'], ['peps','custo_medio'],
  ['desconto_incondicional','desconto_condicional'], ['cmv','cpv'], ['municipal','estadual'], ['municipal','federal'],
  ['estadual','federal'], ['cbs','ibs'], ['diario','razao'], ['exaustao','amortizacao'], ['exaustao','depreciacao'],
  ['amortizacao','depreciacao']
];
/* Opostos que dependem da frase ("o ativo é menor que o passivo" = "o passivo é maior"):
   valem para respostas curtas, mas não para explicações. */
export const CONTEXT_OPPOSITES = [
  ['aumentar','diminuir'], ['receber','pagar'], ['antes','depois'], ['evitar','detectar'], ['data','periodo'],
  ['separado','misturar'], ['confiavel','conflito'], ['direitos','obrigacoes']
];

/* Palavras soltas que também são opostas entre si (fora dos conceitos acima). */
export const OPPOSITE_WORDS = [
  ['ativo','passivo'], ['receita','despesa'], ['entrada','saída'], ['entrar','sair'], ['cliente','fornecedor'],
  ['compra','venda'], ['comprar','vender'], ['maior','menor'], ['mais','menos'], ['acima','abaixo'],
  ['bruto','líquido'], ['direto','indireto'], ['ganho','perda'], ['positivo','negativo'], ['certo','errado'],
  ['sempre','nunca'], ['igual','diferente'], ['junto','separado'], ['parcial','imparcial'], ['dependente','independente'],
  ['preventivo','detectivo'], ['interno','externo'], ['circulante','permanente']
];
