/* Revisão integrada: perguntas novas que misturam o que foi aprendido em lições diferentes de uma
   mesma trilha. Só aparecem nos treinos de revisão (o halter), nunca dentro das lições.

   Cada pergunta declara em `covers` as lições de que depende. Ela só entra num treino quando todas
   essas lições já foram concluídas e fazem parte do que aquele treino revisa. Toda pergunta vale
   sozinha, sem depender de outra, porque o treino embaralha tudo. */
import { mc, tf, fl, en, cl, nu, od } from '../engine/exercises/factories.js';
import { planilha } from './render-helpers.js';

const rv = (covers, x) => Object.assign(x, { covers });

export const REVIEW_BANK = {
  antes: [
    rv(['antes9'], nu('O aluguel de uma loja subiu de R$ 2.000 para R$ 2.300. Qual foi o aumento em %?', 15, 'A variação foi 300 ÷ 2.000 = 0,15, ou seja, 15%.', '%')),
    rv(['antes2'], nu('Uma conta de energia de R$ 1.200 é dividida entre três setores na proporção da área: 20 m², 30 m² e 50 m². Quanto fica com o setor de 30 m²?', 360, 'A área total é 100 m², e esse setor usa 30% dela: 1.200 × 0,30 = 360.', 'R$')),
    rv(['antes6', 'antes1'], mc('Uma TV custa R$ 1.000 à vista ou 5 parcelas de R$ 220. Quanto a mais se paga no parcelado?', ['*R$ 100 a mais: 10% sobre o preço à vista', 'R$ 220 a mais: o valor de uma parcela inteira', 'R$ 100 a menos: parcelar sempre sai mais barato', 'Nada a mais: parcelar não muda o total pago'], '5 × 220 = 1.100. São R$ 100 além dos R$ 1.000 à vista, ou seja, 10%.')),
    rv(['antes4'], nu('R$ 5.000 aplicados a 2% ao mês, a juros compostos, por 2 meses. Qual o montante?', 5202, '1º mês: 5.000 × 1,02 = 5.100. 2º mês: 5.100 × 1,02 = 5.202.', 'R$')),
    rv(['antes7', 'antes8'], cl('Cada item é um documento ou uma forma de pagamento?', ['Documento', 'Forma de pagamento'], 'Nota fiscal:0|Recibo:0|Pix:1|TED:1|Cartão de débito:1', 'Nota fiscal e recibo comprovam a operação. Pix, TED e cartão são maneiras de mover o dinheiro.')),
    rv(['antes3', 'antes8'], tf('Um saldo de −R$ 300 na conta corrente significa que o banco deve R$ 300 ao cliente.', false, 'Saldo negativo significa que o cliente usou dinheiro que não tinha: é ele quem deve ao banco.')),
    rv(['antes10', 'antes6'], nu('Uma padaria vendeu 50 pães a R$ 1,00 e 150 pães a R$ 0,80. Qual o preço médio por pão?', 0.85, 'Média ponderada: (50 × 1,00 + 150 × 0,80) ÷ 200 = 170 ÷ 200 = 0,85.', 'R$', undefined, 0.004))
  ],
  base: [
    rv(['base2'], cl('Bem, direito ou obrigação?', ['Bem', 'Direito', 'Obrigação'], 'Estoque de mercadorias:0|Valores a receber de clientes:1|Salários a pagar:2|Máquina da fábrica:0|Empréstimo bancário:2', 'Bens a empresa possui, direitos ela tem a receber e obrigações ela deve pagar.')),
    rv(['base3'], nu('Uma empresa tem R$ 90.000 de ativos e R$ 35.000 de passivos. Qual o patrimônio líquido?', 55000, 'Ativo − Passivo = PL: 90.000 − 35.000 = 55.000.', 'R$')),
    rv(['base4', 'base6'], mc('Em março a empresa prestou um serviço de R$ 2.000, e o cliente só pagou em abril. Pelo regime de competência, a receita pertence a:', ['*Março, o mês em que o serviço foi prestado', 'Abril, o mês em que o dinheiro entrou', 'Metade a cada mês, dividida igualmente', 'Nenhum mês, até o cliente pagar tudo'], 'A competência olha para quando o fato acontece, não para quando o dinheiro se move.')),
    rv(['base4'], tf('Pagar uma dívida com um fornecedor reduz o lucro do mês.', false, 'Pagar dívida troca dinheiro por menos obrigação. Só receitas, custos e despesas mudam o lucro.')),
    rv(['base4', 'base3'], nu('Receitas de R$ 12.000, custos de R$ 5.000 e despesas de R$ 4.500. Qual o resultado do período?', 2500, 'Resultado = receitas − custos − despesas = 12.000 − 5.000 − 4.500 = 2.500 de lucro.', 'R$')),
    rv(['base5'], mc('Qual afirmação sobre o plano de contas está correta?', ['*Organiza as contas em grupos, para todo fato ter um lugar', 'Lista apenas as contas que terminaram o mês com algum saldo', 'Muda de estrutura a cada lançamento novo do mês', 'É obrigatório só para empresas de grande porte'], 'O plano de contas dá nome e lugar a cada conta, e o mesmo fato sempre cai na mesma conta.')),
    rv(['basex1'], fl('A empresa e o {sócio} são pessoas diferentes: as contas dela não se misturam com as do dono.', ['fornecedor', 'cliente'], 'Entidade: o patrimônio da empresa é separado do patrimônio pessoal dos sócios.'))
  ],
  dc: [
    rv(['dc3'], en('Compra de mercadorias a prazo, R$ 3.000.', 'Estoques', 'Fornecedores', ['Caixa', 'CMV'], 'Entra estoque (débito) e surge a dívida com o fornecedor (crédito).')),
    rv(['dc4'], en('Recebimento de R$ 1.500 de um cliente, via Pix, de uma venda já registrada.', 'Bancos', 'Clientes', ['Receita de vendas', 'Caixa'], 'O dinheiro entra no banco (débito) e o direito de receber diminui (crédito). Não é receita nova.')),
    rv(['dcx3'], en('Depreciação do mês de uma máquina, R$ 400.', 'Despesa de depreciação', 'Depreciação acumulada', ['Máquinas e equipamentos', 'Caixa'], 'A despesa do mês vai a débito; a depreciação acumulada, conta redutora do ativo, recebe o crédito.')),
    rv(['dc2'], mc('Qual destas contas aumenta quando é lançada a crédito?', ['*Fornecedores', 'Caixa', 'Despesa de aluguel', 'Estoques'], 'Passivo aumenta a crédito. Ativo e despesa aumentam a débito.')),
    rv(['dc5'], tf('Para corrigir um lançamento errado, o certo é apagar a linha no livro contábil.', false, 'O certo é estornar: um lançamento inverso, mantendo o rastro do erro e da correção.')),
    rv(['dcx2', 'dc2'], nu('Saldos devedores: Bancos 6.000, Estoques 4.000 e Despesas 1.000. Saldos credores: Fornecedores 2.500, Receitas 3.000 e Capital social. Quanto é o Capital social para o balancete fechar?', 5500, 'Devedores: 6.000 + 4.000 + 1.000 = 11.000. Credores conhecidos: 2.500 + 3.000 = 5.500. O Capital fecha a conta: 11.000 − 5.500 = 5.500.', 'R$')),
    rv(['dc6'], mc('No encerramento do período, o saldo das contas de receita e despesa vai para:', ['*A apuração do resultado, que leva o lucro ao patrimônio líquido', 'O caixa, que fica com o saldo de tudo o que foi pago no período', 'O passivo, onde ficam registradas as dívidas dos sócios com a empresa', 'O estoque, que passa a valer menos depois de cada venda feita'], 'As contas de resultado zeram para o próximo período; o resultado final entra no patrimônio líquido.'))
  ],
  lanc: [
    rv(['lanc7'], en('Provisão do 13º salário do mês, R$ 700.', 'Despesa com 13º salário', '13º salário a pagar', ['Salários a pagar', 'Bancos'], 'Um doze avos do 13º vira despesa todo mês, e a obrigação fica registrada no passivo.')),
    rv(['lanc3'], en('Juros do mês de um empréstimo, R$ 300, para pagar mais tarde.', 'Despesa de juros', 'Juros a pagar', ['Empréstimos a pagar', 'Bancos'], 'Os juros do mês são despesa financeira; a obrigação de pagar fica em Juros a pagar.')),
    rv(['lanc1', 'lanc8'], nu('Uma loja vendeu mercadorias por R$ 9.000, e o custo delas foi R$ 5.400. Qual o lucro bruto?', 3600, 'Lucro bruto = vendas − CMV = 9.000 − 5.400 = 3.600.', 'R$')),
    rv(['lancx1'], nu('Venda de R$ 8.000 no cartão, com taxa de 2,5%. Quanto a empresa vai receber?', 7800, 'A taxa é 2,5% de 8.000 = 200. A empresa recebe 8.000 − 200 = 7.800.', 'R$')),
    rv(['lanc9'], mc('A provisão para devedores duvidosos serve para:', ['*Reconhecer já no resultado a perda provável com clientes', 'Cancelar a dívida de um cliente e apagar o registro dele', 'Cobrar juros dos clientes que pagam com atraso', 'Separar dinheiro em outra conta para pagar fornecedores'], 'É uma estimativa: a perda provável é despesa agora, mesmo antes de o calote acontecer.')),
    rv(['lancx2'], mc('Um cliente paga R$ 4.000 adiantados por um serviço que será feito no mês que vem. Como isso aparece no balanço hoje?', ['*Passivo, como adiantamento de clientes', 'Receita do mês, porque o dinheiro já entrou no caixa', 'Ativo: valores a receber desse mesmo cliente', 'Despesa antecipada no valor de R$ 4.000'], 'Enquanto o serviço não foi feito, a empresa deve o serviço ao cliente: é obrigação, não receita.'))
  ],
  digital: [
    rv(['digital1'], mc('Um arquivo de nota fiscal eletrônica chegou ao sistema da empresa. O que isso significa para a contabilidade?', ['*O documento existe, mas precisa virar lançamento conferido', 'O fato já está registrado e dispensa qualquer conferência posterior', 'A empresa já pagou o valor que consta no documento', 'A despesa já foi reconhecida no resultado do mês'], 'Um arquivo não é um lançamento: alguém, ou uma regra bem testada, precisa conferir e registrar.')),
    rv(['digital3'], mc('No extrato há uma tarifa de R$ 35 que não aparece no razão. O que fazer na conciliação?', ['*Confirmar a tarifa e lançá-la com o documento de apoio', 'Ajustar o saldo do razão até ele bater com o extrato', 'Ignorar a diferença, porque o valor é muito pequeno', 'Pedir ao banco que estorne a tarifa antes de lançar'], 'Diferença pequena continua sendo diferença: registre o fato com evidência, sem forçar o saldo.')),
    rv(['digital2', 'digitalx2'], mc('No ERP, a conta do lançamento é “Despesa com energia”. O que indica qual setor gastou?', ['*O centro de custo informado no lançamento', 'A data em que o lançamento foi digitado', 'O número do documento fiscal de origem', 'O saldo da conta no balancete do mês'], 'A conta diz o que foi gasto. O centro de custo diz onde.')),
    rv(['digital5'], od('Ordene o fechamento digital:', ['Conciliar as contas e lançar os ajustes', 'Conferir o balancete e as diferenças', 'Fechar o período no sistema', 'Gerar e transmitir o arquivo da ECD'], 'Fecha-se o período só depois de conferir tudo, e o arquivo é gerado sobre números já fechados.')),
    rv(['digital6', 'digitalx1'], mc('A mesma pessoa cadastra o fornecedor, aprova a compra e libera o pagamento. Qual o principal problema?', ['*Falta de segregação de funções: um erro passa sem ser visto', 'Excesso de conferência, o que atrasa todos os pagamentos do mês', 'Uso incorreto do centro de custo em cada lançamento feito', 'Falta de integração entre os módulos do sistema contábil'], 'Autorizar, registrar e pagar devem ficar com pessoas diferentes.')),
    rv(['digital6'], tf('Automatizar um lançamento com uma regra errada reduz o erro, porque o sistema nunca se engana.', false, 'A automação repete a regra: se ela estiver errada, o erro se espalha por todos os lançamentos.')),
    rv(['digitalx4'], mc('Qual prática protege melhor os dados de funcionários guardados no sistema contábil?', ['*Dar acesso só a quem precisa e registrar quem consultou', 'Compartilhar a senha da equipe para agilizar o trabalho', 'Enviar a folha de pagamento por aplicativo de mensagens', 'Guardar planilhas com CPFs na área de trabalho do computador'], 'Acesso mínimo necessário e registro de consultas reduzem o risco de vazamento.'))
  ],
  imob: [
    rv(['imob1'], nu('Máquina de R$ 40.000, frete de R$ 2.000 e instalação necessária de R$ 3.000. Sem tributos recuperáveis, qual o custo inicial do bem?', 45000, 'O custo inclui tudo o que é necessário para deixar o bem pronto para uso: 40.000 + 2.000 + 3.000 = 45.000.', 'R$')),
    rv(['imob1', 'imobx2'], cl('Cada gasto vai para o Imobilizado (capitalizar) ou para despesa?', ['Capitalizar', 'Despesa'], 'Instalação necessária para usar a máquina:0|Troca de óleo de rotina:1|Reforma que aumenta a vida útil do bem:0|Conserto de uma peça gasta:1', 'Gastos que deixam o bem pronto ou o fazem durar mais entram no ativo. Manutenção normal é despesa.')),
    rv(['imob2', 'imobx1'], nu('Bem de R$ 60.000, valor residual de R$ 6.000 e vida útil de 6 anos. Qual a depreciação linear por ano?', 9000, '(60.000 − 6.000) ÷ 6 = 9.000 por ano.', 'R$')),
    rv(['imob3'], nu('Um bem custou R$ 50.000 e tem R$ 32.000 de depreciação acumulada. Foi vendido por R$ 21.000. Qual o ganho na venda?', 3000, 'Valor contábil: 50.000 − 32.000 = 18.000. Vendido por 21.000, deu ganho de 3.000.', 'R$')),
    rv(['imob4', 'imobx3'], mc('Uma marca comprada de terceiros, com prazo de uso de 10 anos, é um intangível. Como o custo dela é distribuído no tempo?', ['*Por amortização, ao longo dos 10 anos', 'Por depreciação, como qualquer bem físico', 'Por exaustão, como uma jazida ou floresta', 'Não é distribuído: fica parado até a venda'], 'Intangível com vida útil definida se amortiza. Depreciação é de bens físicos e exaustão, de recursos naturais.')),
    rv(['imob5'], mc('Uma máquina está no balanço por R$ 80.000, mas só pode gerar ou vender por R$ 65.000. O que a contabilidade faz?', ['*Reconhece perda de R$ 15.000 por valor recuperável', 'Mantém os R$ 80.000, pois o custo original não muda', 'Reconhece um ganho de R$ 15.000 por valorização', 'Vende a máquina e registra o valor no caixa'], 'O ativo não pode valer mais do que se pode recuperar: a diferença de R$ 15.000 é perda (impairment).')),
    rv(['imobx4'], tf('Um terreno se deprecia, assim como o prédio que está sobre ele.', false, 'Em regra, o terreno tem vida útil indefinida e não se deprecia. O prédio, sim.'))
  ],
  estoq: [
    rv(['estoq2'], nu('Compra de mercadorias por R$ 10.000, com frete de R$ 500 pago pelo comprador e ICMS recuperável de R$ 1.200 incluído no preço. Qual o custo de aquisição do estoque?', 9300, 'Custo = preço + frete − tributos recuperáveis: 10.000 + 500 − 1.200 = 9.300.', 'R$')),
    rv(['estoq4'], nu('Estoque inicial de R$ 8.000, compras de R$ 20.000 e estoque final de R$ 6.000. Qual o CMV?', 22000, 'CMV = EI + compras − EF = 8.000 + 20.000 − 6.000 = 22.000.', 'R$')),
    rv(['estoq3'], nu('Estoque de 50 unidades a R$ 10 e de outras 50 a R$ 14, nessa ordem de entrada. Vendendo 60 unidades pelo PEPS, qual o CMV?', 640, 'PEPS: as 50 mais antigas e 10 das mais novas. 50 × 10 + 10 × 14 = 500 + 140 = 640.', 'R$')),
    rv(['estoq3'], nu('Estoque de 50 unidades a R$ 10 e de outras 50 a R$ 14. Vendendo 60 unidades pelo custo médio ponderado, qual o CMV?', 720, 'Custo médio = (500 + 700) ÷ 100 = 12. CMV = 60 × 12 = 720.', 'R$')),
    rv(['estoq5', 'estoqx4'], mc('Mercadorias custaram R$ 200, mas só podem ser vendidas por R$ 170 líquidos das despesas de venda. Por quanto o estoque deve ficar no balanço?', ['*R$ 170, o menor entre o custo e o valor realizável', 'R$ 200, porque o custo original nunca se altera', 'R$ 185, a média entre o custo e o valor realizável', 'R$ 30, apenas a diferença entre os dois valores'], 'O estoque vale o menor entre o custo e o valor realizável líquido. A diferença de R$ 30 é perda.')),
    rv(['estoqx3'], nu('Estoque médio de R$ 50.000 e CMV do ano de R$ 300.000. Quantos dias o estoque leva, em média, para girar? (ano de 360 dias)', 60, 'Giro = 300.000 ÷ 50.000 = 6 vezes ao ano. Em dias: 360 ÷ 6 = 60.', 'dias')),
    rv(['estoq1', 'estoqx1'], tf('No inventário periódico, o CMV só é apurado depois da contagem do estoque, no fim do período.', true, 'O periódico apura o CMV pela fórmula EI + compras − EF, depois da contagem. O permanente atualiza a cada venda.'))
  ],
  demo: [
    rv(['demo2'], nu('Receita líquida de R$ 500.000, CMV de R$ 300.000 e despesas operacionais de R$ 120.000. Qual o resultado operacional?', 80000, 'Lucro bruto: 500.000 − 300.000 = 200.000. Menos 120.000 de despesas, sobram 80.000.', 'R$')),
    rv(['demo4', 'demox3'], nu('Ativo circulante de R$ 240.000 e passivo circulante de R$ 160.000. Qual a liquidez corrente? (use vírgula)', 1.5, '240.000 ÷ 160.000 = 1,5.', '', undefined, 0.01)),
    rv(['demo3'], cl('Em qual atividade da DFC entra cada fato?', ['Operacional', 'Investimento', 'Financiamento'], 'Pagamento a fornecedores:0|Compra de um caminhão:1|Empréstimo obtido no banco:2|Recebimento de clientes:0|Venda de um imóvel da empresa:1', 'Operacional é o dia a dia; investimento mexe em ativos de longo prazo; financiamento envolve sócios e credores.')),
    rv(['demox1', 'demo3'], mc('Uma empresa teve lucro de R$ 40.000 no mês, mas o caixa caiu. Qual explicação é possível?', ['*As vendas foram a prazo e os clientes ainda não pagaram', 'A depreciação do mês foi paga em dinheiro ao banco', 'O lucro sempre é igual ao dinheiro que entrou no mês', 'Os sócios aportaram capital, e isso reduziu o caixa'], 'Lucro segue a competência; o caixa só muda quando o dinheiro entra ou sai. Venda a prazo dá lucro sem caixa.')),
    rv(['demo6'], nu('Prazo médio de estocagem de 40 dias, de recebimento de 25 dias e de pagamento de 30 dias. Qual o ciclo financeiro, em dias?', 35, 'Ciclo financeiro = estocagem + recebimento − pagamento = 40 + 25 − 30 = 35.', 'dias')),
    rv(['demox2'], nu('Lucro líquido de R$ 30.000 sobre vendas líquidas de R$ 600.000. Qual a margem líquida em %?', 5, '30.000 ÷ 600.000 = 0,05 = 5%.', '%')),
    rv(['demox4'], nu('Lucro líquido de R$ 45.000 e patrimônio líquido de R$ 300.000. Qual o ROE em %?', 15, '45.000 ÷ 300.000 = 0,15 = 15%.', '%'))
  ],
  cust: [
    rv(['cust2'], nu('Custo fixo de R$ 30.000 por mês e produção de 5.000 unidades. Qual o custo fixo por unidade?', 6, '30.000 ÷ 5.000 = 6. Se a produção dobrar, o fixo por unidade cai para 3.', 'R$')),
    rv(['cust3'], nu('Preço de R$ 50, custo variável de R$ 30 por unidade e custos fixos de R$ 40.000. Qual o ponto de equilíbrio, em unidades?', 2000, 'Margem de contribuição unitária: 50 − 30 = 20. Ponto de equilíbrio: 40.000 ÷ 20 = 2.000.', 'unidades')),
    rv(['cust3', 'custx2'], nu('Com preço de R$ 50, custo variável de R$ 30 e fixos de R$ 40.000, a empresa vende 2.500 unidades. Qual a margem de segurança em %?', 20, 'O ponto de equilíbrio é 2.000 unidades. Margem de segurança = (2.500 − 2.000) ÷ 2.500 = 20%.', '%')),
    rv(['cust6'], nu('Um produto custa R$ 60. Impostos, comissões e margem desejada somam 40% do preço de venda. Qual o preço pelo mark-up divisor?', 100, 'Preço = custo ÷ (1 − 0,40) = 60 ÷ 0,60 = 100.', 'R$')),
    rv(['cust1'], cl('Cada gasto é custo ou despesa?', ['Custo', 'Despesa'], 'Matéria-prima da fábrica:0|Salário do vendedor:1|Energia usada na produção:0|Aluguel do escritório administrativo:1', 'Custo é o gasto para produzir; despesa é o gasto para vender e administrar.')),
    rv(['cust5'], mc('Numa fábrica, qual diferença entre custeio por absorção e custeio variável está correta?', ['*Na absorção, o fixo de fábrica entra no custo do produto', 'No variável, o custo fixo de fábrica entra no estoque do produto', 'Na absorção, só o custo variável entra no produto', 'Os dois dão sempre o mesmo lucro em qualquer mês'], 'A absorção leva todos os custos de produção ao produto; o variável trata o fixo como despesa do período.')),
    rv(['cust4'], mc('A despesa com marketing realizada ficou acima do orçado. Como essa variação é classificada?', ['*Desfavorável, pois o gasto passou do planejado', 'Favorável, porque a empresa investiu mais em vendas', 'Neutra, porque despesa não entra em orçamento', 'Favorável, porque toda variação para cima é boa'], 'Para uma despesa, gastar mais que o previsto é variação desfavorável.'))
  ],
  trib: [
    rv(['trib1'], cl('Cada tributo é direto ou indireto?', ['Direto', 'Indireto'], 'Imposto de renda:0|ICMS:1|IPTU:0|ISS:1', 'Os indiretos vêm embutidos no preço do consumo (ICMS, ISS). Os diretos incidem sobre a renda ou o patrimônio (IR, IPTU).')),
    rv(['trib3', 'tribx3'], nu('Alíquota fictícia de 10%, não cumulativa. Uma loja compra por R$ 4.000 e vende por R$ 6.500. Quanto recolhe de tributo?', 250, 'Débito na venda: 650. Crédito da compra: 400. A loja recolhe 650 − 400 = 250.', 'R$')),
    rv(['trib4'], mc('Uma empresa muda o momento de uma operação, dentro da lei, para pagar menos tributo. Isso é:', ['*Elisão fiscal, um planejamento dentro da lei', 'Evasão fiscal, que esconde a operação do Fisco', 'Sonegação, mesmo quando a lei permite a mudança', 'Anistia, concedida pelo governo à empresa'], 'Elisão é planejamento lícito. Evasão é esconder ou fraudar para pagar menos.')),
    rv(['tribx2'], tf('Entregar uma declaração fora do prazo é descumprir uma obrigação acessória, mesmo que o imposto tenha sido pago.', true, 'A obrigação principal é pagar; a acessória é informar (declarações, escrituração). As duas importam.')),
    rv(['tribx4', 'trib1'], cl('Cada tributo incide sobre vendas ou sobre o lucro?', ['Sobre vendas', 'Sobre o lucro'], 'ICMS:0|ISS:0|IRPJ:1|CSLL:1', 'ICMS e ISS incidem sobre a venda de mercadorias e serviços. IRPJ e CSLL incidem sobre o lucro.'))
  ],
  aud: [
    rv(['aud2'], nu('Uma empresa tem receita de R$ 5.000.000, e a auditoria adota 1% da receita como materialidade. Qual o valor da materialidade?', 50000, '1% de 5.000.000 = 50.000. Erros acima disso podem influenciar as decisões dos usuários.', 'R$')),
    rv(['aud3'], cl('Cada controle é preventivo ou detectivo?', ['Preventivo', 'Detectivo'], 'Aprovação de compras acima de um valor:0|Conciliação bancária mensal:1|Senha para acessar o sistema:0|Revisão de diferenças no inventário:1', 'Os preventivos evitam o erro antes de acontecer. Os detectivos o encontram depois.')),
    rv(['aud4'], mc('Qual evidência costuma ser mais confiável para o auditor?', ['*Um documento externo, como o extrato enviado direto pelo banco', 'Uma planilha de controle feita pela própria empresa auditada', 'Uma explicação verbal dada pelo gerente da área auditada', 'Um relatório interno sem assinatura, sem data e sem revisão'], 'Evidência de fonte externa e independente pesa mais que a produzida pela própria empresa.')),
    rv(['aud5'], mc('O auditor encontra uma distorção relevante, mas restrita a uma parte das demonstrações. Qual opinião é adequada?', ['*Opinião com ressalva', 'Opinião sem ressalva', 'Opinião adversa', 'Abstenção de opinião'], 'Ressalva: distorção relevante, mas não generalizada. Adversa: relevante e generalizada.')),
    rv(['aud6'], mc('Segundo o triângulo da fraude, o que acompanha a oportunidade e a racionalização?', ['*A pressão, o incentivo para cometer a fraude', 'A auditoria interna, que revisa os controles', 'A amostragem, que limita o volume examinado', 'A materialidade, que define o erro relevante'], 'Os três lados são pressão (incentivo), oportunidade e racionalização.')),
    rv(['aud1', 'audx4'], tf('Um auditor externo com participação societária relevante na empresa auditada mantém sua independência normalmente.', false, 'Um interesse financeiro relevante ameaça a independência: o auditor precisa ser imparcial.')),
    rv(['audx2'], mc('Por que o auditor usa amostragem em vez de examinar todos os documentos?', ['*Examinar tudo custa tempo demais, e uma boa amostra basta', 'A lei proíbe o auditor de olhar todos os documentos da empresa', 'Os documentos fora da amostra não têm nenhum risco de erro', 'A amostra elimina qualquer chance de erro na conclusão final'], 'Uma amostra bem escolhida dá segurança razoável sem examinar tudo, embora sempre reste algum risco.'))
  ],
  vida: [
    rv(['vida1'], nu('Você tem bens e dinheiro que somam R$ 80.000 e dívidas de R$ 30.000. Qual o seu patrimônio líquido pessoal?', 50000, 'Ativo − passivo: 80.000 − 30.000 = 50.000.', 'R$')),
    rv(['vida2'], nu('Pela regra 50-30-20, quanto de uma renda líquida de R$ 4.000 vai para as necessidades?', 2000, '50% de 4.000 = 2.000 para necessidades. Os outros 30% (1.200) são desejos e 20% (800), poupança.', 'R$')),
    rv(['vida3'], mc('Você usa o cheque especial e tem uma aplicação que rende pouco. Depois de guardar a reserva mínima, o que costuma fazer mais sentido?', ['*Quitar a dívida cara com parte do dinheiro aplicado', 'Manter a dívida e aplicar ainda mais dinheiro todo mês', 'Pagar só o mínimo e gastar o restante no mês', 'Trocar a dívida por outra com juros parecidos'], 'Os juros do cheque especial costumam ser muito maiores que o rendimento de uma aplicação simples.')),
    rv(['vidax1'], mc('Sua renda subiu 5% em um ano em que a inflação foi de 8%. O que aconteceu com o seu poder de compra?', ['*Diminuiu, porque os preços subiram mais que a renda', 'Aumentou, porque a renda cresceu durante o ano', 'Ficou igual, porque os dois percentuais se anulam', 'Dobrou, porque os dois percentuais se somam'], 'Se os preços sobem mais que a renda, o mesmo dinheiro compra menos: o ganho real foi negativo.')),
    rv(['vidax2'], tf('Pagar só o valor mínimo da fatura do cartão de crédito é uma forma barata de financiar a compra.', false, 'O saldo restante entra no rotativo, com juros altos. É uma das dívidas mais caras que existem.')),
    rv(['vidax4'], mc('Qual indicador mostra o custo total de um financiamento, incluindo juros, tarifas e seguros?', ['*O CET, o Custo Efetivo Total do contrato', 'A parcela mensal informada no contrato', 'A taxa de juros nominal do anúncio', 'O valor total do bem que foi financiado'], 'O CET reúne todos os custos do financiamento e permite comparar propostas.')),
    rv(['emprego1'], nu('Salário bruto de R$ 3.000 com descontos de R$ 350. Qual o líquido que cai na conta?', 2650, 'Líquido = bruto − descontos = 3.000 − 350 = 2.650.', 'R$'))
  ],
  financeirojr: [
    rv(['fj4'], mc('Chegou uma nota de R$ 3.000 do fornecedor, mas a ordem de compra era de R$ 2.500. O que fazer antes de pagar?', ['*Conferir com o pedido e tratar a divergência', 'Pagar o valor da nota, para não atrasar o vencimento', 'Pagar apenas R$ 2.500 e ignorar a diferença de R$ 500', 'Devolver a nota ao fornecedor sem avisar ninguém'], 'A divergência entre pedido e nota se resolve antes do pagamento, com o fornecedor.')),
    rv(['fj6'], nu('Uma fatura de R$ 1.000 foi paga com 1 mês de atraso. Multa de 2% e juros de mora de 1% ao mês. Qual o total pago?', 1030, 'Multa: 2% de 1.000 = 20. Juros: 1% de 1.000 = 10. Total: 1.000 + 20 + 10 = 1.030.', 'R$')),
    rv(['fj9'], tf('Uma empresa pode ter lucro no mês e, mesmo assim, ficar sem dinheiro em caixa.', true, 'Vendas a prazo, compra de estoque e pagamento de dívidas mexem no caixa sem passar pelo lucro do mês.')),
    rv(['fj8'], nu('Saldo inicial de R$ 15.000, recebimentos de R$ 40.000 e pagamentos de R$ 47.000 no mês. Qual o saldo final de caixa?', 8000, '15.000 + 40.000 − 47.000 = 8.000.', 'R$')),
    rv(['fj13'], nu('Nota de serviço de R$ 2.000 com 5% de ISS retido. Quanto será pago ao prestador?', 1900, 'Retenção: 5% de 2.000 = 100. O prestador recebe 2.000 − 100 = 1.900, e a empresa recolhe os 100 à prefeitura.', 'R$')),
    rv(['fj14'], mc('Um colega pede, por mensagem, a lista de salários da empresa para “ajudar num projeto”. O que fazer?', ['*Não enviar e perguntar ao gestor se isso é permitido', 'Enviar a lista completa, já que o colega faz parte da empresa', 'Enviar só os salários dos diretores, sem os nomes', 'Enviar uma foto da tela, para não deixar arquivo'], 'Dado de folha é sigiloso: só se compartilha com autorização e finalidade claras.'))
  ],
  car_excel: [
    rv(['xl2'], mc('Na célula C2 está =B2*$F$1. Copiando a fórmula para C3, ela vira:', ['*=B3*$F$1', '=B3*$F$2', '=B2*$F$1', '=B3*F2'], 'B2 é relativa e acompanha a linha. $F$1 está travada e não muda ao copiar.')),
    rv(['xl9', 'xl10'], mc('O PROCV devolve #N/D, mas o código parece existir na tabela. Qual a causa mais provável?', ['*Espaço extra ou número armazenado como texto no código', 'Excesso de ponto e vírgula entre os argumentos da fórmula', 'A versão do Excel instalada está desatualizada', 'A tabela dinâmica da planilha ainda não foi atualizada'], 'Códigos que parecem iguais podem diferir por espaço ou por tipo (texto x número). Use ARRUMAR ou converta o tipo.')),
    rv(['xl13'], nu(planilha([['Nota', 'Centro', 'Valor'], ['1001', 'TI', '800'], ['1002', 'RH', '500'], ['1003', 'TI', '1.200'], ['1004', 'TI', '300']]) + 'Qual o resultado de =SOMASES(C2:C5; B2:B5; "TI")?', 2300, 'Só as linhas com Centro = TI entram: 800 + 1.200 + 300 = 2.300.')),
    rv(['xl16', 'xl19'], mc('Qual ferramenta mostra o total por centro de custo e por mês, sem escrever fórmulas, e precisa ser atualizada quando a base muda?', ['*Tabela dinâmica', 'PROCV', 'SE aninhado', 'Validação de dados'], 'A tabela dinâmica resume a base por campos arrastados e se atualiza com o comando Atualizar.')),
    rv(['xl6', 'xl16'], tf('Linhas em branco e totais no meio da base atrapalham a criação de uma tabela dinâmica.', true, 'A base deve ser uma tabela limpa: cabeçalho único, sem linhas vazias, sem totais e sem células mescladas.')),
    rv(['xl11'], mc('Você precisa buscar um valor numa coluna que fica à esquerda da coluna de busca. O que resolve?', ['*PROCX, ou ÍNDICE combinado com CORRESP', 'PROCV com o último argumento em FALSO', 'SOMASE com o critério na primeira coluna', 'CONT.SES com dois intervalos de critérios'], 'O PROCV só devolve colunas à direita da coluna de busca. PROCX e ÍNDICE + CORRESP não têm essa limitação.'))
  ],
  car_orcamento: [
    rv(['orc3'], nu('Centro de Marketing: previsto de R$ 80.000, realizado de R$ 52.000 e comprometido em ordens de compra de R$ 18.000. Quanto está disponível?', 10000, 'Disponível = previsto − realizado − comprometido = 80.000 − 52.000 − 18.000 = 10.000.', 'R$')),
    rv(['orc5'], nu('Uma despesa tinha previsto de R$ 50.000 e realizado de R$ 56.000. Qual a variação em %?', 12, 'A variação foi 6.000 ÷ 50.000 = 12%, desfavorável por ser despesa.', '%')),
    rv(['orc5'], mc('A receita de eventos foi de R$ 34.000, contra R$ 40.000 previstos. Como classificar a variação?', ['*Desfavorável, pois a receita ficou abaixo do previsto', 'Favorável, pois o valor realizado é menor que o previsto', 'Neutra, pois variação de receita não é analisada', 'Favorável, pois sobrou verba no orçamento da área'], 'Para receita, ficar abaixo do previsto é desfavorável. Para despesa, é o contrário.')),
    rv(['orc7'], nu('Previsto: 100 unidades a R$ 20. Realizado: 100 unidades a R$ 23. Qual a variação de preço, em R$?', 300, 'O volume foi o previsto. O preço subiu R$ 3 em 100 unidades: variação de preço de R$ 300.', 'R$')),
    rv(['orc9'], nu('Num mês foram pagos 240 títulos, 216 deles em dia. Qual a pontualidade em %?', 90, 'Pontualidade = pagos em dia ÷ total pago = 216 ÷ 240 = 90%.', '%')),
    rv(['orc8'], tf('Uma despesa lançada no centro de custo errado pode fazer um centro estourar e outro parecer que economizou, sem que nada tenha mudado de verdade.', true, 'O total da empresa é o mesmo, mas a análise por centro fica distorcida. Por isso se confere o centro antes de fechar.')),
    rv(['orc11'], mc('Num relatório mensal para o gestor, o que deve aparecer logo no começo?', ['*Um resumo curto do que importa e do que exige decisão', 'A lista completa de todos os lançamentos do mês', 'O histórico de todos os meses de anos anteriores', 'O detalhamento de cada nota fiscal recebida'], 'O gestor lê em dois minutos: resumo primeiro, depois a tabela por centro e os comentários das variações relevantes.'))
  ],
  car_rotina: [
    rv(['rot8', 'rot10'], nu('Nota de serviço de R$ 10.000 com IRRF de 1,5% e CSRF (PIS, COFINS e CSLL) de 4,65% retidos. Ignorando ISS e INSS, qual o valor líquido a pagar ao prestador?', 9385, 'IRRF: 150. CSRF: 465. Líquido: 10.000 − 150 − 465 = 9.385.', 'R$')),
    rv(['rot5'], mc('Uma NF-e saiu com o valor errado. A carta de correção (CC-e) resolve?', ['*Não: valor não pode ser corrigido por CC-e', 'Sim: a CC-e permite corrigir qualquer campo da nota', 'Sim, desde que a diferença seja menor que 10%', 'Sim, se o cliente concordar por e-mail com a correção'], 'A CC-e não pode corrigir valor, impostos, quantidade, partes, datas nem parcelas.')),
    rv(['rot9'], nu('O total a reter de PIS, COFINS e CSLL numa nota é de R$ 8. Pela dispensa estudada, quanto deve ser retido?', 0, 'Quando o valor a reter é de até R$ 10, a retenção é dispensada: nada é retido.', 'R$')),
    rv(['rot11'], tf('Em 2026, a CBS e o IBS têm alíquotas de teste de 0,9% e 0,1%, respectivamente.', true, 'Em 2026 é o ano de teste da Reforma Tributária, com CBS de 0,9% e IBS de 0,1%.')),
    rv(['rot12'], mc('A proposta de menor preço entrega em 45 dias, mas a necessidade é para daqui a 10 dias. O que fazer na cotação?', ['*Comparar também prazo e condições, não só o preço', 'Fechar com o menor preço, porque só o preço importa', 'Fechar com o maior preço, pois é sempre o mais seguro', 'Pedir ao fornecedor que entregue antes sem alterar o preço'], 'Cotação compara preço, prazo, condições e risco. O menor preço só vale se atender à necessidade.')),
    rv(['rot13'], mc('Chegaram 90 caixas, mas a ordem de compra e a nota dizem 100. O que fazer no recebimento?', ['*Receber as 90 caixas e tratar a diferença com o fornecedor', 'Assinar a nota de 100 caixas e resolver a diferença só depois', 'Recusar a entrega inteira, mesmo com as 90 caixas corretas', 'Alterar a ordem de compra para 90 sem avisar o fornecedor'], 'Divergência se resolve no recebimento: só o que chegou é aceito, e a diferença vira pendência com o fornecedor.')),
    rv(['rot14'], nu('Contrato de R$ 20.000 por mês, com reajuste anual de 5% pelo índice previsto. Qual o novo valor mensal após o reajuste?', 21000, 'Reajuste: 5% de 20.000 = 1.000. Novo valor: 20.000 + 1.000 = 21.000.', 'R$'))
  ],
  car_entrevista: [
    rv(['ent5'], mc('Qual sequência descreve o método STAR para contar uma experiência?', ['*Situação, tarefa, ação e resultado', 'Sonho, talento, ambição e recompensa', 'Sistema, técnica, análise e relatório', 'Setor, tempo, aprendizado e realização'], 'STAR: Situação, Tarefa, Ação e Resultado. Termine sempre com o que mudou por causa da sua ação.')),
    rv(['ent4'], mc('Ao responder “fale sobre você” para uma vaga de analista financeiro, o que fazer?', ['*Resumir sua trajetória em dois minutos, ligando-a à vaga', 'Contar sua vida desde a infância, com todos os detalhes', 'Ler o currículo inteiro em voz alta, palavra por palavra', 'Falar só o nome e o cargo atual, para ser objetivo'], 'Uma resposta curta, com trajetória, ponto forte e ligação com a vaga, mostra clareza.')),
    rv(['ent6'], mc('Como responder bem à pergunta “qual é o seu ponto fraco?”', ['*Citar um ponto real e o que você faz para melhorá-lo', 'Dizer que não tem nenhum ponto fraco', 'Citar uma qualidade disfarçada de defeito, como ser perfeccionista', 'Dizer que prefere não responder a essa pergunta'], 'Autoconhecimento e ação de melhoria valem mais que uma resposta ensaiada demais.')),
    rv(['ent7', 'ent8'], mc('Na conferência em três vias, quais documentos são comparados antes de lançar e pagar?', ['*Ordem de compra, comprovante de recebimento e nota fiscal', 'Nota fiscal, extrato bancário e balanço patrimonial', 'Contrato, DRE e fluxo de caixa do período', 'Cotação, folha de pagamento e boleto do fornecedor'], 'Comparar o que foi pedido, o que chegou e o que foi cobrado evita pagar por algo que não foi entregue.')),
    rv(['ent14'], od('Ordene a preparação para a entrevista:', ['Reler a vaga e escolher suas histórias', 'Pesquisar a empresa e o entrevistador', 'Testar o caminho e o horário de chegada', 'Chegar com alguns minutos de antecedência'], 'Primeiro o conteúdo, depois a logística, e por fim a chegada tranquila.')),
    rv(['ent13'], tf('Fazer perguntas ao entrevistador no fim da conversa mostra interesse pela vaga.', true, 'Perguntas sobre a rotina, os indicadores e o que se espera no primeiro mês mostram preparo e interesse.'))
  ]
};
