/* Dicas rotativas mostradas na tela inicial. */

export const TIPS = [
 "Débito não é dívida: é só o nome do lado esquerdo da conta.",
 "Ativo e Despesa aumentam no débito. Passivo, PL e Receita aumentam no crédito.",
 "Todo lançamento precisa de um documento que o comprove.",
 "Lucro não é caixa: vender a prazo gera lucro antes de o dinheiro entrar.",
 "10% de um valor? Divida por 10. 1%? Divida por 100.",
 "Terrenos não sofrem depreciação.",
 "Pagou adiantado? Fica no Ativo até ser usado.",
 "Receita pertence ao mês em que foi ganha, não ao mês em que foi recebida.",
 "O PL é o que sobra para os sócios depois de pagar todas as dívidas.",
 "Empréstimo não é receita: é dívida.",
 "Balancete fechado não garante ausência de erros.",
 "O método UEPS não é aceito no Brasil.",
 "Contas redutoras têm natureza oposta ao grupo em que estão.",
 "O Balanço é uma fotografia; a DRE é um filme.",
 "Liquidez corrente acima de 1: mais recursos que dívidas de curto prazo.",
 "Custo fixo por unidade cai quando a produção aumenta.",
 "No ponto de equilíbrio, o lucro é zero.",
 "O auditor oferece segurança razoável, não absoluta.",
 "Segregação de funções: quem aprova não paga.",
 "A transição da Reforma Tributária vai de 2026 a 2033.",
 "O DAS reúne vários tributos do Simples Nacional numa guia só.",
 "Salário é despesa do mês trabalhado, mesmo pago no mês seguinte.",
 "O FGTS é de 8% sobre a remuneração.",
 "Estorno é o lançamento original ao contrário.",
 "Reserva de emergência: uma referência comum é de 3 a 6 meses de gastos essenciais.",
 "Juros compostos são juros sobre juros.",
 "Castores constroem represas tronco por tronco. Contabilidade se aprende lançamento por lançamento! 🦫",
 "Depositar o caixa no banco não muda o total do Ativo.",
 "Quem vende a prazo ganha um direito; quem compra a prazo ganha uma dívida.",
 "O saldo de uma conta leva o nome do lado maior.",
 "Estudar 10 minutos todo dia vale mais que 2 horas uma vez por semana."
];
